### ISSUE TITLE
question about chunk.size

### ISSUE THREAD

**Issue by cz354** [suchestoncampbelllab/gwasurvivr#15]
I set chunk.size to be 10000. But it stops running after only doing analysis of one chunk.

Analyzing part 1/829...
Analysis completed on 2021-01-04 at 12:55:39

The function I use is plinkCoxSurv.

How should I use it to analysis the all  8290000 SNPs? should I set the chunk.size to be the number of snps?

**Comment by lifeming** [comment]
Hello, I have exactly the same question here. The program stops after one chunk. please advice. Thanks!

**Comment by samkleeman1** [comment]
Same problem!! Program stops after one chunk

**Comment by lsuchest** [comment]
> Hi @cz354 @lifeming @samkleeman1 This has been addressed by @aarizvi

**Comment by cz354** [comment]
Thank you for your response.
